services:
  postgres:
    image: postgres:16-alpine
    container_name: drhched_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         # ej: drhched
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # ej: Siempreseguro.2025
      POSTGRES_DB: ${POSTGRES_DB}             # ej: drhched (la default del init)
      TZ: "America/Mexico_City"
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/sql:/docker-entrypoint-initdb.d:ro  # ‚Üê monta scripts (sh + sql)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
